"""add missing fields

Revision ID: 4dfbad769d3d
Revises: 73cf22db777f
Create Date: 2026-07-16 15:55:05.852693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dfbad769d3d'
down_revision: Union[str, None] = '73cf22db777f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('opd_fees', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'opd_fees')
    # ### end Alembic commands ###
