"""Add OTP fields to Patient

Revision ID: ba53ba628a09
Revises: 4dfbad769d3d
Create Date: 2026-08-03 11:48:06.213992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ba53ba628a09'
down_revision: Union[str, None] = '4dfbad769d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'payment_status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'PENDING'"))
    op.alter_column('appointments', 'consultation_status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'PENDING'"))
    # op.add_column('patients', sa.Column('otp', sa.String(length=10), nullable=True))
    # op.add_column('patients', sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
    op.add_column('patients', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'is_active')
    op.drop_column('patients', 'otp_expires_at')
    op.drop_column('patients', 'otp')
    op.alter_column('appointments', 'consultation_status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'PENDING'"))
    op.alter_column('appointments', 'payment_status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'PENDING'"))
    # ### end Alembic commands ###
